name: dart_architect
description: An app showcasing Flutter components, with side-by-side source code view.

version: 0.1.1+2

environment:
  sdk: ">=3.2.0-0 <4.0.0"

publish_to: none

dependencies:
  animated_radial_menu: ^0.0.1
  animated_text_kit: ^4.2.1
  animations: ^2.0.1
  async: null
  backdrop: ^0.9.0
  badges: ^3.0.3
  cached_network_image: ^3.1.0
  community_charts_flutter: ^1.0.1
  chat_gpt_sdk: ^2.0.6

  community_material_icon: ^5.9.55
  convex_bottom_bar: ^3.0.0
  day_night_switcher: ^0.2.0+1
  device_preview: ^1.1.0
  device_preview_screenshot: ^1.0.0
  edge_detection: ^1.0.7
  english_words: ^4.0.0
  extended_image: ^8.0.2
  feature_discovery: ^0.14.0
  ffi: ^2.0.1
  fl_chart: ^0.63.0
  #TODO add YaMetrics

  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_gallery_assets: ^1.0.2
  flutter_heatmap_calendar: ^1.0.5
  flutter_highlight: ^0.7.0
  flutter_markdown: ^0.6.12
  flutter_quill: ^7.0.4
  flutter_radar_chart: ^0.2.0
  flutter_riverpod: ^2.0.2
  flutter_slidable: ^3.0.0
  flutter_state_notifier: ^1.0.0
  flutter_whatsnew:
    path: packages/flutter_whatsnew-master
  flutterfire_ui: ^0.4.2
  fluttertoast: ^8.0.7
  freezed_annotation: ^2.0.3
  google_fonts: ^5.1.0
  google_ml_kit: ^0.16.1
  google_mobile_ads: ^3.0.0
  graphview: ^1.1.1
  heatmap_calendar:
    git:
      url: https://github.com/CouldI/flutter_heatmap_calendar.git
  hidable: ^1.0.2
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^1.0.0
  image: ^4.0.15
  in_app_purchase: ^3.0.8
  in_app_review: ^2.0.4
  intl: ^0.18.0
  introduction_screen: ^3.0.2
  like_button: ^2.0.5
  local_auth: ^2.0.0
  lottie: ^2.3.1
  markdown: ^7.0.2
  package_info_plus: ^4.0.2
  path: ^1.8.0
  path_provider: ^2.0.2
  photo_view: ^0.14.0
  provider: ^6.0.2
  scoped_model: ^2.0.0-nullsafety.0
  selectable: ^0.3.0
  sembast: ^3.1.0+2
  share_plus: ^7.0.2
  shared_preferences: ^2.0.6
  shimmer: ^3.0.0
  sqflite: ^2.0.0+3
  state_notifier: ^1.0.0
  substring_highlight: ^1.0.33
  transparent_image: ^2.0.0
  tuple: ^2.0.0
  url_launcher: ^6.0.9
  video_player: ^2.1.12
  widget_with_codeview: ^3.1.0

dev_dependencies:
  build_runner: ^2.0.6
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.1.6
  freezed: ^2.0.3
  hive_generator: ^2.0.0
  json_serializable: null
  lint: ^2.0.1

# $ flutter pub run flutter_launcher_icons:main
# Cf. https://pub.dev/packages/flutter_launcher_icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: res/images/app_icon2.png

# $ flutter pub run flutter_native_splash:create
# Cf. https://pub.dev/packages/flutter_native_splash
flutter_native_splash:
  color: "#f7f7f7"
  image: res/images/app_icon2.png

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  # Note: when new assets are added, have to run `flutter clean` to see
  # changes take effect.
  assets:
    - CHANGELOG.md
    - lib/routes/
    - lib/example/
    - lib/routes/data/
    - res/images/
    - res/lottie/
    - packages/flutter_gallery_assets/animated_images/animated_flutter_stickers.webp
    - screenshots/Screenshot01.png
